apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-greencity-chat
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-greencity-chat
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-greencity-chat
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: {{ .Release.Name }}-greencity-chat
        image: {{ .Values.deployment.image }}
        resources:
          requests:
            cpu: {{ .Values.deployment.requests.cpu }}
            memory: {{ .Values.deployment.requests.memory }}
          limits:
            cpu: {{ .Values.deployment.limits.cpu }}
            memory: {{ .Values.deployment.limits.memory }}
        startupProbe:
          httpGet:
              path: /swagger-ui.html
              port: 8070
          periodSeconds: 10
          failureThreshold: 20
        env:
        - name: AZURE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: AZURE-CONTAINER

        - name: AZURE_CONNECTION
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: AZURE-CONNECTION

        - name: CLIENT_ADDRESS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: CLIENT-ADDRESS

        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: DATABASE-PASSWORD

        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: DATABASE-USER

        # - name: DATASOURCE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ .Values.externalSecret.secretName }}
        #       key: API-KEY

        - name: DIALECT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: DIALECT

        - name: DRIVER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: DRIVER

        - name: GREENCITYUSER_SERVER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: GREENCITYUSER-SERVER-ADDRESS

        - name: HIBERNATE_CONFIG
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: HIBERNATE-CONFIG

        - name: JAWSDB_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: {{ if eq .Values.environment "prod" }}JAWSDB-URL{{ else }}JAWSDB-URL-TEST{{ end }}

        - name: LOG_EXCEPTION_HANDLER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: LOG-EXCEPTION-HANDLER

        - name: LOG_FILE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: LOG-FILE

        - name: LOG_LEVEL_ROOT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: LOG-LEVEL-ROOT

        - name: LOG_PATH
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: LOG-PATH

        - name: LOG_PATTERN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: LOG-PATTERN

        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: SPRING-PROFILES-ACTIVE

        - name: TOKEN_ACCESS_TIME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: TOKEN-ACCESS-TIME

        - name: TOKEN_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: TOKEN-KEY

        - name: TOKEN_REFRESH_TIME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: TOKEN-REFRESH-TIME

        - name: VERIFY_EMAIL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.secretName }}
              key: VERIFY-EMAIL
        ports:
        - containerPort: 8070
          name: tomcat
