trigger:
  batch: true
  branches:
    include:
    - prod
  paths:
    exclude:
    - README.md

pr: none

variables:
  jsonFile: google-creds.json
  jsonLocation: /site/wwwroot

  agentOS: ubuntu-latest

  azKeyVault: key-vault-greencity
  jsonSecret: google-credentials

  artifactName: drop
  userRepoName: chat
  onbootJarName: app.jar

  azureSub: GreenCity2022
  resourceGroup: GreenCity
  userServiceName: greencity-chat

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@3
            displayName: Maven package
            inputs:
              mavenPomFile: 'pom.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              mavenVersionOption: 'Default'
              options: '-Dmaven.test.skip=true'

          - script: mv $(userRepoName)/target/*.jar $(userRepoName)/target/$(onbootJarName)
            displayName: Rename user jar to app

          - task: CopyFiles@2
            displayName: Copy Files
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)'
              Contents: '**/target/*.jar'
              TargetFolder: '$(build.artifactstagingdirectory)'
          
          - task: CopyFiles@2
            displayName: Copy Files
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)/greencity-chat-chart'
              Contents: '**'
              TargetFolder: '$(build.artifactstagingdirectory)/greencity-chat-chart'

          - task: PublishBuildArtifacts@1
            displayName: Publish Artifact
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
              artifactName: '$(artifactName)'
              
          - task: Docker@2
            inputs:
              containerRegistry: 'Dockerhub_Skyere'
              repository: 'skyere/greencitychat'
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile'
              tags: |
                prod-$(Build.BuildId)
                latest

  - stage: deploy
    jobs:
      - deployment: deploy
        displayName: Deploy GreenCityChat
        pool:
          vmImage: $(agentOS)
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none

                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: '$(artifactName)'
                    downloadPath: '$(System.ArtifactsDirectory)'

                - task: HelmInstaller@0
                  inputs:
                    helmVersion: '3.9.0'
                    installKubectl: true
                
                - task: HelmDeploy@0
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceConnection: 'production'
                    namespace: 'default'
                    command: 'upgrade'
                    chartType: 'FilePath'
                    chartPath: '$(System.ArtifactsDirectory)/drop/greencity-chat-chart'
                    releaseName: 'chat'
                    overrideValues: 'ingress.hostname=greencity-chat.pick-up.city,deployment.image=skyere/greencitychat:prod-$(Build.BuildId),ingress.cors_allow_origin=https://www.pick-up.city/*'
                    arguments: '--debug '

